version: "3.8"
name: agile-software-effort-estimation-system
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/images/app/Dockerfile
    volumes:
      - ..:/app
    depends_on:
      - mysql
    networks:
      - app_network

  api:
    build:
      context: ../
      dockerfile: ./docker/images/fastapi/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    depends_on:
      - app
    networks:
      - app_network

  jupyter:
    build:
      context: ../
      dockerfile: ./docker/images/jupyter/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/project
    depends_on:
      - app
    networks:
      - app_network

  mysql:
    image: mariadb:10.9.4
    env_file: ../.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
