import random

ISSUE_STATUSES = [
    'To Do',
    'Done',
    'In PR',
    'In Progress',
    'Open',
    'Closed',
    'Resolved',
    'Waiting for Feedback',
    'New',
    'In Development',
    'Waiting for Review',
    'To Be Tested',
    'Testing In Progress',
    'Raw',
    'Ready for Development',
    'Refine',
    'Ready to Groom',
    'Accepted',
    'Reviewable',
    'Patch Available',
    'Reopened',
    'In Review',
    'Gathering Interest',
    'Needs Triage',
    'Long Term Backlog',
    'Short Term Backlog',
    'Gathering Impact',
    'Under Consideration',
    'Future Consideration',
    'Waiting for Release',
    'Not Being Considered',
    'Reviewing',
    'Awaiting Release',
    'Published',
    'Awaiting Merge',
    'Complete',
    'Backlog',
    'Planning',
    'To Test',
    'Code Review',
    'To Develop',
    'Unverified',
    'In CR Review',
    'Returned',
    'Reviewed',
    'Invalid',
    "Won't Fix",
    'Selected for Development',
    'Debugging With Submitter',
    'Ready for Work',
    'Scoping',
    'In Code Review',
    'Investigating',
    'Waiting (Blocked)',
    'Waiting for Reporter',
    'Scheduled',
    'Needs Design',
    'Debugging',
    'Waiting for peer review',
    'Development in progress',
    'Tested',
    'Waiting for integration review',
    'Peer review in progress',
    'Integration review in progress',  # Status_0
    'Testing in progress',
    'Waiting for testing',
    'Triaged',
    'In QE Test',
    'Planned Development',
    'Pull Request Submitted',
    'Automation',
    'Needs Scheduling',
    'Needs Verification',
    'Needs Merge',
    'Waiting For User Input',
    'Blocked'
]

RESOLUTION_STATUSES = [
    'Unknown',
    'Complete',
    'Invalid',
    'Works as Designed',
    'Deferred',
    "Won't Fix",
    'Cannot Reproduce',
    'Incomplete',
    'Duplicate',
    'Fixed',
    'Done',
    'Not A Bug',
    'Automatically Closed',
    'Parked',
    'Out of scope',
    "Won't Do",
    'Resolved',
    'Not A Problem',
    'Implemented',
    'Information Provided',
    'Later',
    'Abandoned',
    'Feedback Received',
    'Workaround',
    'Works for Me',
    'Pending Closed',
    'Not Our Bug',
    'Needs more info',
    'Hold',
    'Tracked Elsewhere',
    'Handled by Support',
    'Obsolete',
    'Not a bug',
    'Support Request',
    'Answered',
    'Timed out',
    'Resolved Locally',
    'Unsolved Mysteries',
    'Incorrectly Filed',
    'Deployed',
    'Spam',
    'Invalid: Works as Expected',
    'Invalid: Environment Issue',
    'Invalid: Test Error',
    'Invalid: Not Supported',
    'Ready for Test',
    'Ready for Release',
    'Community Answered',
    'Declined',
    'Gone away',
    'Inactive',
    'Completed',
    "Won't Fix or Usage Issue",
    'Rejected',
    'Unresolved'
]

DEFAULTS = {
    'Jira_ID': str(random.randint(10, 99999)),
    'Total_Effort_Minutes': 0,
    'In_Progress_Minutes': 0,
    'Resolution_Time_Minutes': 0,
    'Story_Point_Changed_After_Estimation': 0,
    'Sprint_ID': str(random.randint(10, 99999)),
    'Resolution_1': 0,
    'Resolution_0': 0,
    'Title_Changed_After_Estimation': 0,
    'Resolution_3': 0,
    'Assignee_ID': str(random.randint(100, 99999)),
    'Resolution_5': 1 # Unknown
}